### ISSUE TITLE
将对应的插件支持到最新版，发现引入主题模块报错

### ISSUE THREAD

**Issue by 52lemon** [wtx358/wtxlog#10]
源代码引入的是flask-themes,提示找不到，我改成了flask-themes2
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_mobility\decorators.py", line 35, in wrapper
    return f(*args, **kwargs)
  File "E:\PycharmProjects\wtxlog\wtxlog\ext.py", line 200, in decorated_function
    rv = f(*args, **kwargs)
  File "E:\PycharmProjects\wtxlog\wtxlog\main\views.py", line 53, in index
    pagination=pagination)
  File "E:\PycharmProjects\wtxlog\wtxlog\utils\helpers.py", line 14, in render_template
    return render_theme_template(get_current_theme(), template, **context)
  File "E:\PycharmProjects\wtxlog\wtxlog\utils\helpers.py", line 10, in get_current_theme
    return get_theme(current_app.config.get('THEME', 'default'))
  File "C:\Python27\lib\site-packages\flask_themes2\__init__.py", line 156, in get_theme
    return ctx.app.theme_manager.themes[ident]
KeyError: 'imtx'

不知道如何修改，还请指点！
还有这个模块，from flask import Module，提示没有Module模块，我该怎么处理

**Comment by wtx358** [comment]
请使用虚拟环境, 并按照 `requirements.txt` 安装依赖.

由于 Flask 不同版本对插件的处理不太一样, 有可能会出现无法引入的问题. 本项目使用 Flask 0.10.x 版本.

**Comment by 52lemon** [comment]
有没有计划将对应的插件升级到最新版本

**Comment by wtx358** [comment]
@52lemon 目前没有这方面的计划, 抱歉
