### ISSUE TITLE
设置为CMS 模式出错

### ISSUE THREAD

**Issue by XianchaoZhang** [wtx358/wtxlog#8]
修改：
```
-    BLOG_MODE = True
+    BLOG_MODE = False
```

访问主页： http://127.0.0.1:5000/

错误log：

```
Traceback (most recent call last):
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask_mobility/decorators.py", line 35, in wrapper
    return f(*args, **kwargs)
  File "/media/disk/apps/wiki/wtxlog/wtxlog/ext.py", line 200, in decorated_function
    rv = f(*args, **kwargs)
  File "/media/disk/apps/wiki/wtxlog/wtxlog/main/views.py", line 55, in index
    return render_template(_template)
  File "/media/disk/apps/wiki/wtxlog/wtxlog/utils/helpers.py", line 14, in render_template
    return render_theme_template(get_current_theme(), template, **context)
  File "/media/disk/apps/wiki/wtxlog/mydeps/flask_themes.py", line 471, in render_theme_template
    **context)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/media/disk/apps/wiki/wtxlog/wtxlog/themes/imtx/templates/index.html", line 1, in top-level template code
    {% extends theme('layout.html') %}
  File "/media/disk/apps/wiki/wtxlog/wtxlog/themes/imtx/templates/layout.html", line 4, in top-level template code
    <title>{% block fulltitle%}{% block title %}{% endblock %} - {{ config['SITE_NAME'] }}{% endblock %}</title>
  File "/media/disk/apps/wiki/wtxlog/wtxlog/themes/imtx/templates/index.html", line 3, in block "fulltitle"
    {% block fulltitle %}{{ label('index_title') or config['SITE_NAME'] }}{% if pagination.page>1 %}_?{{ pagination.page }}?{% endif %}{% endblock %}
  File "/media/disk/apps/wiki/myenv/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'pagination' is undefined
```

**Comment by wtx358** [comment]
@XianchaoZhang 感谢你的反馈, 这个问题已经修正了.

CMS模式下, 首页是没有默认布局的, 需要自己定制.
